/**
 * Native bindings to Rust core
 * 
 * napi-rs will generate the actual bindings during build.
 * This file provides the TypeScript interface that matches the Rust function.
 */

import type { AnnotationResult } from './annotations';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import os from 'os';

/**
 * Result of segmentation from native bindings
 * 
 * Note: Field names match the Rust struct (snake_case) as returned by serde_json
 */
export interface SegmentResult {
  /** Array of sentence strings */
  sentences: string[];
  /** End-of-sentence indices (UTF-16 code units) */
  eos_indices: number[];
  /** Annotation layers */
  layers: AnnotationResult['layers'];
}

/**
 * Native segment function
 * 
 * This is the TypeScript interface for the Rust function exported via napi-rs.
 * The actual implementation is generated during `npm run build`.
 * 
 * @param text - Input text to segment
 * @returns Segmentation result with sentences and EOS indices
 */
export declare function segment(text: string): SegmentResult;

// For runtime, we'll use dynamic import to load the native module
// The actual binding will be generated by napi-rs
// Note: Rust returns JSON string, not object
let nativeModule: { segment: (text: string) => string } | null = null;

/**
 * Initialize the native module (called automatically on first use)
 * Uses createRequire for ESM compatibility
 */
function loadNativeModule(): { segment: (text: string) => string } {
  if (nativeModule) {
    return nativeModule;
  }

  try {
    // Use createRequire for ESM compatibility
    const requireModule = createRequire(import.meta.url);
    
    const platform = os.platform();
    const arch = os.arch();
    
    let binaryName = 'fast-bunkai';
    if (platform === 'darwin') {
      binaryName += arch === 'arm64' ? '.darwin-arm64.node' : '.darwin-x64.node';
    } else if (platform === 'linux') {
      binaryName += arch === 'arm64' ? '.linux-arm64-gnu.node' : '.linux-x64-gnu.node';
    } else if (platform === 'win32') {
      binaryName += '.win32-x64-msvc.node';
    } else {
      binaryName += '.node';
    }
    
    // Get current directory in ESM
    const currentDir = dirname(fileURLToPath(import.meta.url));
    const binaryPath = join(currentDir, '..', 'build', binaryName);
    
    // Use require for .node files (CommonJS compatible)
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const loaded = requireModule(binaryPath);
    nativeModule = loaded as { segment: (text: string) => string };
    return nativeModule;
  } catch (error) {
    throw new Error(
      `Native bindings not available. Run "npm run build" first. Error: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}

/**
 * Runtime wrapper for the segment function
 * 
 * @param text - Input text to segment
 * @returns Segmentation result
 */
export function segmentRuntime(text: string): SegmentResult {
  const native = loadNativeModule();
  const jsonString = native.segment(text);
  // Parse JSON string returned from Rust
  return JSON.parse(jsonString) as SegmentResult;
}
