/**
 * Native bindings to Rust core
 * 
 * napi-rs will generate the actual bindings during build.
 * This file provides the TypeScript interface that matches the Rust function.
 */

import type { AnnotationResult } from './annotations';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import os from 'os';

/**
 * Result of segmentation from native bindings
 * 
 * Note: Field names match the Rust struct (snake_case) as returned by serde_json
 */
export interface SegmentResult {
  /** Array of sentence strings */
  sentences: string[];
  /** End-of-sentence indices (UTF-16 code units) */
  eos_indices: number[];
  /** Annotation layers */
  layers: AnnotationResult['layers'];
}

/**
 * Native segment function
 * 
 * This is the TypeScript interface for the Rust function exported via napi-rs.
 * The actual implementation is generated during `npm run build`.
 * 
 * @param text - Input text to segment
 * @returns Segmentation result with sentences and EOS indices
 */
export declare function segment(text: string): SegmentResult;

// For runtime, we'll use dynamic import to load the native module
// The actual binding will be generated by napi-rs
// Note: Rust returns JSON string, not object
let nativeModule: { segment: (text: string) => string } | null = null;

/**
 * Get platform-specific binary name
 * 
 * @returns Binary filename for the current platform
 */
function getPlatformBinaryName(): string {
  const platform = os.platform();
  const arch = os.arch();
  
  if (platform === 'darwin') {
    return arch === 'arm64' ? 'fast-bunkai.darwin-arm64.node' : 'fast-bunkai.darwin-x64.node';
  }
  if (platform === 'linux') {
    return arch === 'arm64' ? 'fast-bunkai.linux-arm64-gnu.node' : 'fast-bunkai.linux-x64-gnu.node';
  }
  if (platform === 'win32') {
    return 'fast-bunkai.win32-x64-msvc.node';
  }
  return 'fast-bunkai.node';
}

/**
 * Initialize the native module (called automatically on first use)
 * Uses createRequire for ESM compatibility
 */
function loadNativeModule(): { segment: (text: string) => string } {
  if (nativeModule) {
    return nativeModule;
  }

  try {
    // Use createRequire for ESM compatibility
    const requireModule = createRequire(import.meta.url);
    
    // Get platform-specific binary name
    const binaryName = getPlatformBinaryName();
    
    // Get current directory in ESM
    const currentDir = dirname(fileURLToPath(import.meta.url));
    const binaryPath = join(currentDir, '..', 'build', binaryName);
    
    // Use require for .node files (CommonJS compatible)
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const loaded = requireModule(binaryPath);
    
    // Type guard to validate the loaded module
    if (typeof loaded?.segment !== 'function') {
      throw new Error('Native module does not export segment function');
    }
    
    nativeModule = { segment: loaded.segment };
    return nativeModule;
  } catch (error) {
    throw new Error(
      `Native bindings not available. Run "npm run build" first. Error: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}

/**
 * Runtime wrapper for the segment function
 * 
 * @param text - Input text to segment
 * @returns Segmentation result
 */
export function segmentRuntime(text: string): SegmentResult {
  const native = loadNativeModule();
  const jsonString = native.segment(text);
  
  // Parse JSON string returned from Rust
  try {
    return JSON.parse(jsonString) as SegmentResult;
  } catch (error) {
    throw new Error(
      `Failed to parse segmentation result from native module: ${error instanceof Error ? error.message : String(error)}`
    );
  }
}
